name: Deploy Build Files

on:
  push:
    branches:
      - main # 只在main上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - uses: actions/checkout@v3 # 第一步，下载代码仓库

      - uses: actions/setup-node@v3
        with:
          node-version: v14.17.6

      - name: INSTALL
        run: yarn install

      - name: BUILD
        run: yarn build

      - name: CLEAR
        run: rm -rf node_modules && pwd && ls

      - name: DEPOLY
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
          SOURCE: './' # 将要复制到云服务器的静态文件夹
          REMOTE_HOST: ${{ secrets.SSH_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          REMOTE_USER: ${{ secrets.SSH_USERNAME }} # 引用配置，服务器登录名
          TARGET: '/home/soul_dev/source/' # 打包后的文件夹将放在目录
          EXCLUDE: '/node_modules/,node_modules/,**/ndoe_modules/,../node_modules/,node_modules/**,../node_modules/**'
