name: Deploy Build Files

on:
  push:
    branches:
      - dev # 只在dev上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE
env:
  TARGET_DEV_DIR: /home/soul/developer/soul
  TARGET_PRD_DIR: /home/soul/production/soul

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - uses: actions/checkout@v3 # 第一步，下载代码仓库

      - uses: actions/setup-node@v3
        with:
          node-version: v14.17.6

      - name: DEPLOY DEV
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: 'Start Deploy'
          LASTSSH: 'Done Deploy'
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PWD }}
          connect_timeout: 10s
          first_ssh: |-
            pwd
          #   ls -la
          #   echo $WELCOME
          #   cd $TARGET_DEV_DIR
          #   git checkout .
          #   git fetch --all
          #   git checkout dev
          #   git pull --force origin dev
          # last_ssh: |-
          #   cd $TARGET_DEV_DIR
          #   whoami
          #   export NVM_DIR=~/.nvm
          #   source ~/.nvm/nvm.sh
          #   yarn install
          #   yarn build
          #   yarn server:dev
          #   pm2 restart all
          #   echo $LASTSSH
